### ISSUE TITLE
[v5] Cannot read properties of undefined (reading 'toString') when using BottomSheetBackdrop

### ISSUE THREAD

**Issue by itsramiel** [gorhom/react-native-scroll-bottom-sheet#1465]
# Bug

I am testing the latest alpha on web and the simple example seems to work, but the backdrop example does not. In my app I use the `BottomSheetBackdrop` component but as soon as I use that I get the following error:
```
utils.ts:83 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at utils.ts:83:1
    at Array.reduce (<anonymous>)
    at buildWorkletsHash (utils.ts:82:1)
    at buildDependencies (utils.ts:106:1)
    at useHandler (utils.ts:66:1)
    at useAnimatedGestureHandler (useAnimatedGestureHandler.ts:49:1)
    at BottomSheetBackdropComponent (BottomSheetBackdrop.tsx:77:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at updateSimpleMemoComponent (react-dom.development.js:19425:1)
```

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 5.0.0-alpha.3   |
| react-native                    | 0.72.3   |
| react-native-reanimated         | 3.3.0   |
| react-native-gesture-handler    | 2.12.0   |

## Steps To Reproduce

1. use latest alpha release `5.0.0-alpha.3` with expo sdk 49 
2. Copy and paste the [backdrop example](https://gorhom.github.io/react-native-bottom-sheet/components/bottomsheetbackdrop#example):
3.  run `npx expo start --web` and you will see the error in the console

Describe what you expected to happen:

1. Have the backdrop render normally

## Reproducible sample code

```
import React, { useCallback, useMemo, useRef } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import BottomSheet, { BottomSheetBackdrop } from '@gorhom/bottom-sheet';

const App = () => {
  // ref
  const bottomSheetRef = useRef<BottomSheet>(null);

  // variables
  const snapPoints = useMemo(() => ['25%', '50%', '75%'], []);

  // callbacks
  const handleSheetChanges = useCallback((index: number) => {
    console.log('handleSheetChanges', index);
  }, []);

  // renders
  const renderBackdrop = useCallback(
    props => (
      <BottomSheetBackdrop
        {...props}
        disappearsOnIndex={1}
        appearsOnIndex={2}
      />
    ),
    []
  );
  return (
    <View style={styles.container}>
      <BottomSheet
        ref={bottomSheetRef}
        index={1}
        snapPoints={snapPoints}
        backdropComponent={renderBackdrop}
        onChange={handleSheetChanges}
      >
        <View style={styles.contentContainer}>
          <Text>Awesome 🎉</Text>
        </View>
      </BottomSheet>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    backgroundColor: 'grey',
  },
  contentContainer: {
    flex: 1,
    alignItems: 'center',
  },
});

export default App;
```

**Comment by itsramiel** [comment]
closing since I don't think this is a bug with this package. Solution for those having a similar issue -> https://github.com/software-mansion/react-native-reanimated/issues/2994#issuecomment-1216482813

**Comment by itsramiel** [comment]
Opening again because I will submit a pr for an internal fix

**Comment by itsramiel** [comment]
still valid
