### ISSUE TITLE
[v4] Jest tests don't run (included a minimal reproduction)

### ISSUE THREAD

**Issue by gersomvg** [gorhom/react-native-scroll-bottom-sheet#932]
# Bug

I have a bigger project that uses this library quite heavily, but when including it in our jest testing suite I run into all kinds of errors.

I've made a minimal reproduction here: https://github.com/gersomvg/bug-bottom-sheet-jest

The error that I run into there isn't exactly the same as the one I have in the bigger project, but I suspect they are related.

**It looks like `@gorhom/bottom-sheet` doesn't play nicely with gesture-handler and reanimated _mocks_.**

<img width="674" alt="image" src="https://user-images.githubusercontent.com/8234283/166432272-ae828096-6c5c-47dc-8cdc-3c0ffeb86e23.png">

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.2.2   |
| react-native                    | 17.0.2   |
| react-native-reanimated         | 2.8.0   |
| react-native-gesture-handler    | 2.4.1 (tried 1.10.3 as well)   |

## Steps To Reproduce

1. Clone this repo: https://github.com/gersomvg/bug-bottom-sheet-jest
2. Follow the three steps in the readme

Describe what you expected to happen:

1. The tests run without error

## Reproducible sample code

https://github.com/gersomvg/bug-bottom-sheet-jest

**Comment by hannibaldinski** [comment]
Having the same issue.

**Comment by gorhom** [comment]
will work on a fix by this week

**Comment by gersomvg** [comment]
@gorhom Amazing! Let me know if there is anything I can help you with, for example testing fixes or adding more docs regarding jest/testing.

I can also try out any possible fixes on our bigger project, to see if it also solves the issues there, since we use a few more bottom-sheet hooks and components in that project.

**Comment by gorhom** [comment]
hi @gersomvg , could you test this branch and let me know if its working ?

```bash
yarn add ssh://github.com/gorhom/react-native-bottom-sheet#refactor/added-jest-mock
```

**Comment by gersomvg** [comment]
Thanks for this @gorhom! I guess this is a good and simple approach to just mock out the lib completely for external consumers, assuming the lib tests its internals itself.

Few issues I ran into:

- The mock for `BottomSheetView` seems to be missing
- It seems like the `yarn add` doesn't generate all needed build files? I couldn't figure out how to build your branch, so I just copied the `mock.js` and `package.json` changes manually to my node_modules. This worked, except for that my typescript code didn't recognise the `mock.js` as a commonjs (?) module, so after mocking, the `BottomSheet` in `import BottomSheet from '@gorhom/react-native-bottom-sheet'` contained everything from `module.exports` in `mock.js`.

After accounting for these two points, my tests ran fine! 🎊

**Comment by gorhom** [comment]
Hi @gersomvg , did the release [v4.3.0](https://github.com/gorhom/react-native-bottom-sheet/releases/tag/v4.3.0) fixes your issue ?

**Comment by PedroRestrepo** [comment]
@gorhom seems like the issue with `toString` is fixed, but was getting the following error because of how the `default` is imported and used in our codebase.

![image](https://user-images.githubusercontent.com/7490699/170330941-8fece32f-fa78-4c6f-a7e6-e5127b12207b.png)

Fixed it by adding `__esModule` to the jest mock so it handles the `default` correctly
```js
jest.mock('@gorhom/bottom-sheet', () => ({
  ...mockBottomSheet,
  __esModule: true,
}));
```

**Comment by gersomvg** [comment]
@gorhom Thanks for the release! I was on holiday, hence the late response. With @PedroRestrepo's fix it works for me.

**Comment by Alaa-Ben** [comment]
Here's what I did, works for me:
```
jest.mock('@gorhom/bottom-sheet', () => ({
  __esModule: true,
  ...require('@gorhom/bottom-sheet/mock')
}))
```

**Comment by pvinis** [comment]
use this:
```
import mockBottomSheet from '@gorhom/bottom-sheet/mock';
jest.mock('@gorhom/bottom-sheet', () => mockBottomSheet);
```

**Comment by anabeatrizzz** [comment]
> Here's what I did, works for me:
> 
> ```
> jest.mock('@gorhom/bottom-sheet', () => ({
>   __esModule: true,
>   ...require('@gorhom/bottom-sheet/mock')
> }))
> ```

I have a screen with three `BottomSheet` components. When I run a test case, all of them are opened on debug tree and overlap a button that must be pressed. Do you have any tips regarding this mock, thus none of the components stay opened?
@Alaa-Ben

**Comment by anniekao** [comment]
@anabeatrizzz were you able to resolve your issue? I'm seeing something similar in tests where the BottomSheetModal is open by default and tests are failing.

**Comment by anabeatrizzz** [comment]
What I did was return `null` based on a `false` condition, otherwise, return the `BottomSheet`

Example:

```typescript
const BottomSheetAnswer = ({ loading }: { loading: boolean }) => {
  return (
    <>
      {loading ? (
        <BottomSheet>
          <View />
        </BottomSheet>
      ) : null}
    </>
  );
};
```

@anniekao

**Comment by vanGalilea** [comment]
@gorhom should I raise a PR to add this to the docs? Pretty crucial, as everyone is wondering what is the best way to handle the bottom-sheet in tests.

**Comment by vanGalilea** [comment]
And shouldn't we render the children conditionally in the render functions of the [mock](https://github.com/gorhom/react-native-bottom-sheet/blob/master/mock.js#L38)?

I've expected the children of to sheet/modal not to be in the dom when the modal/sheet is not actually visible, what are you thought's on this @gorhom ?

**Comment by gpbaculio** [comment]
Had ScrollView problem using Flashlist, this fixed it:

jest.mock("@gorhom/bottom-sheet", () => {
  const originalMock = jest.requireActual("@gorhom/bottom-sheet/mock");
  const { ScrollView } = require("react-native");

  return {
    ...originalMock,
    BottomSheetScrollView: ScrollView, // Override with regular ScrollView
  };
});

**Comment by salatielsql** [comment]
I had a similar issue using when using the `BottomSheetTextInput` I highlighted the fix here #1596

**Comment by Jwiggiff** [comment]
This doesn't seem to be working for me. When I use @pvinis solution I get the following error:
```
TypeError: Cannot read properties of undefined (reading 'default')
```

and when I try @Alaa-Ben solution I get this error:
```
Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /workspaces/oomami/node_modules/@gorhom/bottom-sheet/mock.js:54
          <Content data={this.data} />
          ^

    SyntaxError: Unexpected token '<'

      11 |   __esModule: true,
      12 |   // eslint-disable-next-line @typescript-eslint/no-require-imports
    > 13 |   ...require('@gorhom/bottom-sheet/mock'),
         |      ^
      14 | }));
      15 |
      16 | // Mock react-native-safe-area-context

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at require (__tests__/EmojiPicker.test.tsx:13:6)
      at Object.require (components/home/EmojiPicker.tsx:2:1)
      at Object.require (__tests__/EmojiPicker.test.tsx:4:1)
```

Any idea what I should do to fix this?

**Comment by rachelanordgren** [comment]
Also getting `SyntaxError: Unexpected token '<'` after upgrading from 4.6.1 to 5.1.6

**Comment by ravindraguptacapgemini** [comment]
@rachelanordgren @Jwiggiff  have you found any fix for the issue?

**Comment by ebelair** [comment]
If anyone encounters the `SyntaxError: Unexpected token '<'` issue, here is a workaround I found:

In `jest.config.ts`
```ts
const config: Config = {
  // ...
  transform: {
    // Default transformer
    '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { presets: ['babel-preset-expo'] }],
    // Custom transformer for bottom-sheet mock
    'node_modules/@gorhom/bottom-sheet/mock.js': ['babel-jest', { presets: ['@babel/preset-env', '@babel/preset-react'] }],
  },
  transformIgnorePatterns: [
    'node_modules/(?!(.*react.*|@gorhom|expo.*)/)'
  ],
};
```

**Comment by marcshilling** [comment]
> If anyone encounters the `SyntaxError: Unexpected token '<'` issue, here is a workaround I found:
> 
> In `jest.config.ts`
> 
> const config: Config = {
>   // ...
>   transform: {
>     // Default transformer
>     '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { presets: ['babel-preset-expo'] }],
>     // Custom transformer for bottom-sheet mock
>     'node_modules/@gorhom/bottom-sheet/mock.js': ['babel-jest', { presets: ['@babel/preset-env', '@babel/preset-react'] }],
>   },
>   transformIgnorePatterns: [
>     'node_modules/(?!(.*react.*|@gorhom|expo.*)/)'
>   ],
> };

Thanks! For me, I only needed to add `|@gorhom` to `transformIgnorePatterns`. I don't declare the `transform` key at all.
